version: "3.8"
services:
  web:
    image: munirapp/nodejs-app
    depends_on:
      - db
      - redis
    ports:
      - "5000:5000"
    command: bash -c "bash migrate.sh && npm run prod"

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: standard-api
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: arcs-material
    ports:
      - "8080:8080"
